on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v1
      - name: Setup NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      -name: install python
        run: sudo apt install python3.8-dev
      - name: Install Dependencies
        run: npm install
      - name: Run test
        run: npm test